# Generated by Django 3.2.16 on 2023-03-03 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('processing', models.BooleanField(default=False)),
                ('processing_success', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
